### PR TITLE
Update dependencies (`nextcloud-vue-collections`, `@nextcloud/webpack-vue-config`)

### LINKED ISSUE #9236: "Uncaught TypeError: O.observable is not a function" with @nextcloud/webpack-vue-config 5.5.0
```
$ git bisect log
git bisect start
# status: waiting for both good and bad commits
# good: [e266f44ce9f3f808b2acaef84167101eec224dbe] Merge pull request #9196 from nextcloud/changelog/16.0.2
git bisect good e266f44ce9f3f808b2acaef84167101eec224dbe
# status: waiting for bad commit, 1 good commit known
# bad: [9e928c67db69ead1b96b0240bd69797f8f46c1e1] Merge pull request #9221 from nextcloud/dependabot/npm_and_yarn/extendable-media-recorder-7.1.10
git bisect bad 9e928c67db69ead1b96b0240bd69797f8f46c1e1
# good: [bf4f1723f1b2b3651cc06ee5780426d092191a49] Use avatar instead of picture in non user-facing names
git bisect good bf4f1723f1b2b3651cc06ee5780426d092191a49
# good: [3bbd2fdc25966c6058c78e161fa57208452195af] Merge pull request #9059 from nextcloud/feature/8334/conversation-avatar-frontend
git bisect good 3bbd2fdc25966c6058c78e161fa57208452195af
# bad: [5a51222b12900038fffdf5776590959f6da99a1f] Merge pull request #9092 from nextcloud/dependabot/npm_and_yarn/nextcloud/webpack-vue-config-5.5.0
git bisect bad 5a51222b12900038fffdf5776590959f6da99a1f
# good: [17d06c32b14cda6f2dfc43f144407af600d82e27] post-review improvements
git bisect good 17d06c32b14cda6f2dfc43f144407af600d82e27
# good: [c0a169321c9946af56be52b17ea2229ef2f1eaba] fix lint error, replace find methods for participant name
git bisect good c0a169321c9946af56be52b17ea2229ef2f1eaba
# bad: [46ee916ca57af0f7f45a128797cb9d6123da8e2d] chore(deps-dev): Bump @nextcloud/webpack-vue-config from 5.4.0 to 5.5.0
git bisect bad 46ee916ca57af0f7f45a128797cb9d6123da8e2d
# first bad commit: [46ee916ca57af0f7f45a128797cb9d6123da8e2d] chore(deps-dev): Bump @nextcloud/webpack-vue-config from 5.4.0 to 5.5.0
```

Talk does not load anymore:
```
Uncaught TypeError: O.observable is not a function
    js index.js:286
    Webpack 22
index.js:286
```

```
Uncaught TypeError: O.observable is not a function
    js index.js:286
    Webpack 22
        __webpack_require__
        ./node_modules/babel-loader/lib/index.js!./node_modules/vue-loader/lib/index.js??vue-loader-options!./src/components/RightSidebar/SharedItems/SharedItemsTab.vue?vue&type=script&lang=js&
        __webpack_require__
        ./src/components/RightSidebar/SharedItems/SharedItemsTab.vue?vue&type=script&lang=js&
        __webpack_require__
        vue
        __webpack_require__
        ./node_modules/babel-loader/lib/index.js!./node_modules/vue-loader/lib/index.js??vue-loader-options!./src/components/RightSidebar/RightSidebar.vue?vue&type=script&lang=js&
        __webpack_require__
        ./src/components/RightSidebar/RightSidebar.vue?vue&type=script&lang=js&
        __webpack_require__
        vue
        __webpack_require__
        ./node_modules/babel-loader/lib/index.js!./node_modules/vue-loader/lib/index.js??vue-loader-options!./src/App.vue?vue&type=script&lang=js&
        __webpack_require__
        ./src/App.vue?vue&type=script&lang=js&
        __webpack_require__
        vue
        __webpack_require__
        <anonymous>
        <anonymous>
        <anonymous>
index.js:286
```

_Originally posted by @nickvergessen in https://github.com/nextcloud/spreed/issues/9092#issuecomment-1494253171_

### PR DESCRIPTION
**Pull request by Antreesy**
### ☑️ Resolves

* Fix #9236 
* Bump vue-collections to previous version (v0.11 was migrated from webpack to vite, which probably causes the conflict and broken Talk build, and v0.10 is the last oficial release)
* Update webpack-vue-config to latest version (uninstall and install again)
* Tested with dev and build

### 🏁 Checklist

- [x] ⛑️ Tests (unit and/or integration) are included or not required
- [x] 📘 API documentation in `docs/` has been updated or is not required
- [x] 📗 User documentation in https://github.com/nextcloud/documentation/tree/master/user_manual/talk has been updated or is not required
- [x] 🔖 Capability is added or not needed

### CODE REVIEW

**Comment by nickvergessen** [comment]
I have no clue about such details :(
Let me know if you need someone from another group to verify thoughts or whatever.

**Comment by ShGKme** [comment]
This PR downgrades `nextcloud-vue-collectives` in favor of upgrading `@nextcloud/webpack-vue-config`.
The question is what do we want:
* `nextcloud-vue-collectives` ⬇️ **v0.10.0** with `@nextcloud/webpack-vue-config` ⬆️ **v5.5.0**
* `nextcloud-vue-collectives` ⬆️ **v0.11.0** with `@nextcloud/webpack-vue-config` ⬇️ **v5.4.0**

Both changes are minor.

There is 2 problems with the build:
1. `nextcloud-vue-collectives@0.11.0` provides only CJS bundle which breaks using Vue ESM
2. `@nextcloud/webpack-vue-config` has `resolve.alias: vue$ -> node_modules/vue/` which breaks possibility to use 2 different Vue versions (ESM and CJS) at the same time.

I have no ideas how exactly alias in 2 breaks resolving module type. But it is possible to fix 1 in `nextcloud-vue-collectives`

**Comment by nickvergessen** [comment]
nextcloud-vue-collectives is from the deprecated projects feature iirc? Then i prefer an updated vue webpack

**Comment by nickvergessen** [comment]
Otherwise fix nextcloud-vue-collectives
Upstream

**Comment by Antreesy** [comment]
> Otherwise fix nextcloud-vue-collectives

As upstream library requires a fix, it could be wise to push the green button now, and wait for a proper v0.11.0 release

**Comment by nickvergessen** [comment]
It's deprecated, but still has to remain functional for now

**Comment by ShGKme** [comment]
> Otherwise fix nextcloud-vue-collectives

https://github.com/nextcloud/nextcloud-vue-collections/pull/994

> It's deprecated

🥲

**Comment by ShGKme** [comment]
Note: `nextcloud-vue-collections@0.10.0` had lower major version in many dependencies. Using `0.10.0` means bundling a second (old) copy of `@nextcloud/vue@3`, `@nextcloud/axios@1.x`, `axios@0.x` and other dependencies.

**Comment by nickvergessen** [comment]
Thanks a lot for taking care of it @ShGKme 💙

**Review by ShGKme — APPROVED** [review]
📦
