### ISSUE TITLE
"Uncaught TypeError: O.observable is not a function" with @nextcloud/webpack-vue-config 5.5.0

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/spreed#9236]
```
$ git bisect log
git bisect start
# status: waiting for both good and bad commits
# good: [e266f44ce9f3f808b2acaef84167101eec224dbe] Merge pull request #9196 from nextcloud/changelog/16.0.2
git bisect good e266f44ce9f3f808b2acaef84167101eec224dbe
# status: waiting for bad commit, 1 good commit known
# bad: [9e928c67db69ead1b96b0240bd69797f8f46c1e1] Merge pull request #9221 from nextcloud/dependabot/npm_and_yarn/extendable-media-recorder-7.1.10
git bisect bad 9e928c67db69ead1b96b0240bd69797f8f46c1e1
# good: [bf4f1723f1b2b3651cc06ee5780426d092191a49] Use avatar instead of picture in non user-facing names
git bisect good bf4f1723f1b2b3651cc06ee5780426d092191a49
# good: [3bbd2fdc25966c6058c78e161fa57208452195af] Merge pull request #9059 from nextcloud/feature/8334/conversation-avatar-frontend
git bisect good 3bbd2fdc25966c6058c78e161fa57208452195af
# bad: [5a51222b12900038fffdf5776590959f6da99a1f] Merge pull request #9092 from nextcloud/dependabot/npm_and_yarn/nextcloud/webpack-vue-config-5.5.0
git bisect bad 5a51222b12900038fffdf5776590959f6da99a1f
# good: [17d06c32b14cda6f2dfc43f144407af600d82e27] post-review improvements
git bisect good 17d06c32b14cda6f2dfc43f144407af600d82e27
# good: [c0a169321c9946af56be52b17ea2229ef2f1eaba] fix lint error, replace find methods for participant name
git bisect good c0a169321c9946af56be52b17ea2229ef2f1eaba
# bad: [46ee916ca57af0f7f45a128797cb9d6123da8e2d] chore(deps-dev): Bump @nextcloud/webpack-vue-config from 5.4.0 to 5.5.0
git bisect bad 46ee916ca57af0f7f45a128797cb9d6123da8e2d
# first bad commit: [46ee916ca57af0f7f45a128797cb9d6123da8e2d] chore(deps-dev): Bump @nextcloud/webpack-vue-config from 5.4.0 to 5.5.0
```

Talk does not load anymore:
```
Uncaught TypeError: O.observable is not a function
    js index.js:286
    Webpack 22
index.js:286
```

```
Uncaught TypeError: O.observable is not a function
    js index.js:286
    Webpack 22
        __webpack_require__
        ./node_modules/babel-loader/lib/index.js!./node_modules/vue-loader/lib/index.js??vue-loader-options!./src/components/RightSidebar/SharedItems/SharedItemsTab.vue?vue&type=script&lang=js&
        __webpack_require__
        ./src/components/RightSidebar/SharedItems/SharedItemsTab.vue?vue&type=script&lang=js&
        __webpack_require__
        vue
        __webpack_require__
        ./node_modules/babel-loader/lib/index.js!./node_modules/vue-loader/lib/index.js??vue-loader-options!./src/components/RightSidebar/RightSidebar.vue?vue&type=script&lang=js&
        __webpack_require__
        ./src/components/RightSidebar/RightSidebar.vue?vue&type=script&lang=js&
        __webpack_require__
        vue
        __webpack_require__
        ./node_modules/babel-loader/lib/index.js!./node_modules/vue-loader/lib/index.js??vue-loader-options!./src/App.vue?vue&type=script&lang=js&
        __webpack_require__
        ./src/App.vue?vue&type=script&lang=js&
        __webpack_require__
        vue
        __webpack_require__
        <anonymous>
        <anonymous>
        <anonymous>
index.js:286
```

_Originally posted by @nickvergessen in https://github.com/nextcloud/spreed/issues/9092#issuecomment-1494253171_

**Comment by Antreesy** [comment]
While updating the package, it stucks with `Conflicting peer dependency: webpack-cli@5.0.1`
which was bumped here: https://github.com/nextcloud/webpack-vue-config/commit/e7d8a8b1a98f0b4a4bf6d8b01a79aac9e081f611

If we perform a force install, process will crash at [this place](https://github.com/nextcloud/nextcloud-vue-collections/blob/c9746e6ce024753061928c8e34dcc20a3075afad/src/collectionstore.js#L26-L28):
```js
const state = Vue.observable({
	collections: [],
})
```
